swagger: '2.0'

info:
  version: "1.0"
  title: Dataset API

paths:
  /api/dataset/get/:datasetID:
    get:
      description: |
        Get `Dataset` object as json.
      parameters:
        -
          name: datasetID
          in: query
          description: It's unique id for dataset.
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: Dataset json
          schema:
            title: Dataset JSON
            type: string
  # Post for same path(key).
    post:
      description: |
        Get `Dataset` object as json.
      parameters:
        -
          name: datasetID
          in: query
          description: It's unique id for dataset.
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: Dataset json
          schema:
            title: Dataset JSON
            type: string
  /api/metadata/items:
   get:
      description: |
        Get metadata list by tag(path) and value.
      parameters:
        -
          name: tag
          in: query
          description: tag(path) in metadata json.
          required: true
          type: string
        -
          name: value
          in: query
          description: tag value in metadata json.
          required: true
          type: string
      responses:
        200:
          description: Array of metadata with contains tag(path) and value match(sql like "%value%")
          schema:
            title: Dataset JSON
            type: string
   post:
      description: |
        Get metadata list by tag(path) and value.
      parameters:
        -
          name: tag
          in: query
          description: tag(path) in metadata json.
          required: true
          type: string
        -
          name: value
          in: query
          description: tag value in metadata json.
          required: true
          type: string
      responses:
        200:
          description: Array of metadata with contains tag(path) and value match(sql like "%value%")
          schema:
            title: Dataset JSON
            type: string